name: "deen_transformer_regular"

data:
    src: "de"
    trg: "en"
    train: "test/data/toy/train" #"data/train.bpe"
    dev:   "test/data/toy/dev"  #"data/dev.bpe"
    test:  "test/data/toy/test" #"data/test.bpe"
    level: "bpe"
    lowercase: False
    max_sent_length: 100
    src_vocab: "../mt_fs21_ex4/shared_models/vocab.txt"
    trg_vocab: "../mt_fs21_ex4/shared_models/vocab.txt"

testing:
    beam_size: 5
    alpha: 1.0
    active_layers: [0, 2]

training:
    random_seed: 42
    optimizer: "adam"
    normalization: "tokens"
    learning_rate: 0.0003
    batch_size: 2048
    batch_type: "token"
    eval_batch_size: 1024
    eval_batch_type: "token"
    scheduling: "plateau"
    patience: 8
    weight_decay: 0.0
    decrease_factor: 0.7
    early_stopping_metric: "ppl"
    epochs: 10
    validation_freq: 100
    logging_freq: 100
    eval_metric: "bleu"
    model_dir: "models/deen_transformer_layerdrop_v05"
    overwrite: False
    shuffle: True
    use_cuda: False
    max_output_length: 100
    print_valid_sents: [0, 1, 2, 3, 4]
    label_smoothing: 0.3
    save_latest_ckpt: True

model:
    initializer: "xavier"
    bias_initializer: "zeros"
    init_gain: 1.0
    embed_initializer: "xavier"
    embed_init_gain: 1.0
    tied_embeddings: True
    tied_softmax: True
    encoder:
        type: "transformer"
        num_layers: 4
        num_heads: 2
        embeddings:
            embedding_dim: 256
            scale: True
            dropout: 0
        hidden_size: 256
        ff_size: 512
        dropout: 0
        layerdrop: 0.3
    decoder:
        type: "transformer"
        num_layers: 1
        num_heads: 2
        embeddings:
            embedding_dim: 256
            scale: True
            dropout: 0
        hidden_size: 256
        ff_size: 512
        dropout: 0
